# Generated by Django 4.2.7 on 2025-07-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authors', models.CharField(help_text='Comma-separated list of authors', max_length=300)),
                ('publication', models.CharField(blank=True, help_text='Journal, conference, or venue', max_length=200)),
                ('link', models.URLField(blank=True, help_text='Link to paper or project')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
