# Generated by Django 4.2.7 on 2025-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_researchproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cricheroes_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
    ]
